registration:
    form: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    id: "entry.1111111111"
    name: "entry.1111111111"
attendance:
    form: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    id: "entry.1111111111"
